version: '3'
services:
  notification-service:
    build: ./services/notification  # Adjust to the correct path where the Dockerfile is located
    ports:
      - "6000:6000"  # Map port 5003 on the host to port 5003 in the container
    environment:
      - NODE_ENV=production  # You can add more environment variables if necessary
    restart: always  # Ensures the service restarts automatically if it crashes
