apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: backend
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5050  # Flask app's exposed port
  type: ClusterIP
