apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image:   # Your image for the auth service
          ports:
            - containerPort: 5050
          envFrom:
            - configMapRef:
                name: auth-configmap  # Assuming your configuration is stored in a ConfigMap
            - secretRef:
                name: auth-secret  # Assuming secrets are stored here
