apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
      - name: booking-container
        image: your-dockerhub-username/booking-service:latest
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "yourpassword"
        - name: DB_NAME
          value: "train_booking_db"
        - name: DB_PORT
          value: "5432"
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: booking-service
  namespace: backend
spec:
  selector:
    app: booking-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002  # Application's internal port
  type: ClusterIP
