apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-db
  template:
    metadata:
      labels:
        app: shared-db
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_DB
          value: "train_booking_db"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "yourpassword"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: shared-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP