apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-ticket-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: train-ticket
  template:
    metadata:
      labels:
        app: train-ticket
    spec:
      containers:
      - name: train-ticket-container
        image: your-dockerhub-username/train-ticket-service:latest
        env:
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "yourpassword"
        - name: DB_NAME
          value: "train_booking_db"
        - name: DB_PORT
          value: "5432"
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: train-ticket-service
  namespace: backend
spec:
  selector:
    app: train-ticket-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001  # Application's internal port
  type: ClusterIP
